version: '3.8'

services:
  frontend:
    image: node:20-alpine
    working_dir: /home/app
    ports:
      - "80:4200"
    command: sh -c "npm install -g @angular/cli@19.2.4 && npm install --legacy-peer-deps && ng serve --host 0.0.0.0 --poll=2000 --port 4200 --disable-host-check"
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
    depends_on:
      - backend
    environment:
      NODE_ENV: development

  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME:-frassati_db}
      DB_USER: ${DB_USER:-frassati_user}
      DB_PASSWORD: ${DB_PASSWORD:-frassati_pass}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${DB_NAME:-frassati_db}
      MYSQL_USER: ${DB_USER:-frassati_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-frassati_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data: