version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: frassati_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Backend PHP
  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8000:80"
    
  # Frontend em Angular
  frontend:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data: