version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: frassati_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3307"
    command: --default-authentication-plugin=mysql_native_password

  # Backend PHP
  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
      
    ports:
      - "8000:80"
    depends_on:
      - mysql
    
  # Frontend em Angular
  frontend:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: