version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: frassati-db
    environment:
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_INITDB_ROOT_SERVER_URL: "localhost"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Mantido conforme solicitado
      MYSQL_DATABASE: frassati_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d  # Pasta para scripts SQL iniciais
    ports:
      - "3307:3307"  # Corrigido para porta padrão
    command:
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html  # Montagem para desenvolvimento
    ports:
      - "8000:80"
    depends_on:
      mysql:
        condition: service_healthy  # Espera MySQL ficar pronto

  frontend:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"  # Mantido na porta 80 conforme original
    depends_on:
      - backend

volumes:
  mysql_data: